[package]
name = "shared_code"
version = "0.1.0"
edition = "2024"

[dependencies]
crc32fast = "1.4.2"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
bincode = { version = "2.0.1", features = ["derive"] }
